### ISSUE TITLE
wifi 只支持2.4G 

### ISSUE THREAD

**Issue by sparkmindsacademy** [retro98boy/linux-tn3399_v3#4]
蛮奇怪的，nmtui 里边，只能搜到 2.4G wifi，5G 的wifi SSID 一个都搜不到，会是什么原因？

**Comment by retro98boy** [comment]
> 蛮奇怪的，nmtui 里边，只能搜到 2.4G wifi，5G 的wifi SSID 一个都搜不到，会是什么原因？

这两个系统镜像我都重新开机尝试了下，完全是可以搜到5Ghz频段的WLAN，搜不到可能有两个原因：
1，没加装天线时，5Ghz信号特别弱，搜不到
2，板子只支持802.ac，也就是WIFI 5，不支持WIFI 6的802.ax频段。把路由器5Ghz频段设置成802.ac应该就行了
