### ISSUE TITLE
apt-upgrade后有线网不能用但是WIFI能用

### ISSUE THREAD

**Issue by Not-a-good-username** [retro98boy/linux-tn3399_v3#5]
如题，是Ubuntu那版的系统，刷完后再apt upgrade以后有线就不能用了，但是WIFI可以连接，其他功能sata啊usb啊HDMI啊也都正常。
没有什么明显的报错，iwconfig的那边提示eth0没有东西

这个问题可能有点小白，刚接触，希望大佬指点一下，麻烦大佬(>﹏<)

**Comment by retro98boy** [comment]
我的除错过程：
1，先将板子刷好armbian的系统，执行apt update&&apt upgrade更新后重启，执行ip a命令可以看到eth0设备，但是没有从路由器自动获得ip，之前是可以的，所以的确出现了问题。
2，使用ip addr add 172.16.0.100/16 dev eth0&&ip link set eth0 up给网卡手动配ip并上线，然后ping路由器172.16.0.1，是可以ping通，说明eth0驱动和Linux协议栈没问题
3，目前可以确定网卡使用没问题，只是dhcp获取ip出了问题，网络开机自动配置有很多办法，使用netplan.io包，或者systemd带的networkd，我比较喜欢network-manager，使用systemctl status NetworkMnager命令可以看到network-manager的守护程序正常运行，接着使用nmcli dev show，可以看到eth0为未托管状态。
最终确定了问题所在，系统没有其余的开机自动网络配置工具，唯一开机自动配网的network-manager没有管理eth0，自然不会dhcp到ip了，解决方法，rm -rf /usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf，然后重启，network-manager就会托管eth0了，默认是dhcp，也可以执行nmtui手动配ip。
PS：这个镜像我是删除了不托管网卡的设置的，可能是更新软件后，又自动下载回来了

**Comment by retro98boy** [comment]
> 如题，是Ubuntu那版的系统，刷完后再apt upgrade以后有线就不能用了，但是WIFI可以连接，其他功能sata啊usb啊HDMI啊也都正常。 没有什么明显的报错，iwconfig的那边提示eth0没有东西
> 
> 这个问题可能有点小白，刚接触，希望大佬指点一下，麻烦大佬(>﹏<)

我的除错过程：
1，先将板子刷好armbian的系统，执行apt update&&apt upgrade更新后重启，执行ip a命令可以看到eth0设备，但是没有从路由器自动获得ip，之前是可以的，所以的确出现了问题。
2，使用ip addr add 172.16.0.100/16 dev eth0&&ip link set eth0 up给网卡手动配ip并上线，然后ping路由器172.16.0.1，是可以ping通，说明eth0驱动和Linux协议栈没问题
3，目前可以确定网卡使用没问题，只是dhcp获取ip出了问题，网络开机自动配置有很多办法，使用netplan.io包，或者systemd带的networkd，我比较喜欢network-manager，使用systemctl status NetworkMnager命令可以看到network-manager的守护程序正常运行，接着使用nmcli dev show，可以看到eth0为未托管状态。
最终确定了问题所在，系统没有其余的开机自动网络配置工具，唯一开机自动配网的network-manager没有管理eth0，自然不会dhcp到ip了，解决方法，rm -rf /usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf，然后重启，network-manager就会托管eth0了，默认是dhcp，也可以执行nmtui手动配ip。
PS：这个镜像我是删除了不托管网卡的设置的，可能是更新软件后，又自动下载回来了

**Comment by Not-a-good-username** [comment]
> > 如题，是Ubuntu那版的系统，刷完后再apt upgrade以后有线就不能用了，但是WIFI可以连接，其他功能sata啊usb啊HDMI啊也都正常。 没有什么明显的报错，iwconfig的那边提示eth0没有东西
> > 这个问题可能有点小白，刚接触，希望大佬指点一下，麻烦大佬(>﹏<)
> 
> 我的除错过程： 1，先将板子刷好armbian的系统，执行apt update&&apt upgrade更新后重启，执行ip a命令可以看到eth0设备，但是没有从路由器自动获得ip，之前是可以的，所以的确出现了问题。 2，使用ip addr add 172.16.0.100/16 dev eth0&&ip link set eth0 up给网卡手动配ip并上线，然后ping路由器172.16.0.1，是可以ping通，说明eth0驱动和Linux协议栈没问题 3，目前可以确定网卡使用没问题，只是dhcp获取ip出了问题，网络开机自动配置有很多办法，使用netplan.io包，或者systemd带的networkd，我比较喜欢network-manager，使用systemctl status NetworkMnager命令可以看到network-manager的守护程序正常运行，接着使用nmcli dev show，可以看到eth0为未托管状态。 最终确定了问题所在，系统没有其余的开机自动网络配置工具，唯一开机自动配网的network-manager没有管理eth0，自然不会dhcp到ip了，解决方法，rm -rf /usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf，然后重启，network-manager就会托管eth0了，默认是dhcp，也可以执行nmtui手动配ip。 PS：这个镜像我是删除了不托管网卡的设置的，可能是更新软件后，又自动下载回来了

谢谢，我今晚试试，如果没什么问题我就不回复并且关issue了，感谢大佬

**Comment by Not-a-good-username** [comment]
> > 如题，是Ubuntu那版的系统，刷完后再apt upgrade以后有线就不能用了，但是WIFI可以连接，其他功能sata啊usb啊HDMI啊也都正常。 没有什么明显的报错，iwconfig的那边提示eth0没有东西
> > 这个问题可能有点小白，刚接触，希望大佬指点一下，麻烦大佬(>﹏<)
> 
> 我的除错过程： 1，先将板子刷好armbian的系统，执行apt update&&apt upgrade更新后重启，执行ip a命令可以看到eth0设备，但是没有从路由器自动获得ip，之前是可以的，所以的确出现了问题。 2，使用ip addr add 172.16.0.100/16 dev eth0&&ip link set eth0 up给网卡手动配ip并上线，然后ping路由器172.16.0.1，是可以ping通，说明eth0驱动和Linux协议栈没问题 3，目前可以确定网卡使用没问题，只是dhcp获取ip出了问题，网络开机自动配置有很多办法，使用netplan.io包，或者systemd带的networkd，我比较喜欢network-manager，使用systemctl status NetworkMnager命令可以看到network-manager的守护程序正常运行，接着使用nmcli dev show，可以看到eth0为未托管状态。 最终确定了问题所在，系统没有其余的开机自动网络配置工具，唯一开机自动配网的network-manager没有管理eth0，自然不会dhcp到ip了，解决方法，rm -rf /usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf，然后重启，network-manager就会托管eth0了，默认是dhcp，也可以执行nmtui手动配ip。 PS：这个镜像我是删除了不托管网卡的设置的，可能是更新软件后，又自动下载回来了

好了，但是我没有直接删掉，我担心他下次再回来，修改了一下配置文件，在最后添加了
`,except:type:ethernet`
作用和删掉好像一样，不管怎样解决了
